services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - app-network

  dbmate:
    image: amacneil/dbmate
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DBMATE_MIGRATIONS_DIR=/db/migrations
    command: up
    networks:
      - app-network
    volumes:
      - ./backend/db/migrations:/db/migrations

  openf1:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - OPENF1_API_USERNAME=${OPENF1_API_USERNAME}
      - OPENF1_API_PASSWORD=${OPENF1_API_PASSWORD}
    ports:
      - "8003:8003"
    command: poetry run uvicorn backend.openf1.main:app --host 0.0.0.0 --port 8003
    networks:
      - app-network

  mailings:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_CRYPTAGE=${MAIL_CRYPTAGE}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERLABEL=${MAIL_USERLABEL}
      - MAIL_ALIAS=${MAIL_ALIAS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MAIL_LOGIN=${MAIL_LOGIN}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    ports:
      - "8002:8002"
    command: poetry run uvicorn backend.mailings.main:app --host 0.0.0.0 --port 8002
    networks:
      - app-network

  assets:
    build:
      context: .
      dockerfile: Dockerfile-test
    ports:
      - "8001:8001"
    command: poetry run uvicorn backend.assets.main:app --host 0.0.0.0 --port 8001
    networks:
      - app-network
    volumes:
      - /home/jerand/mygrid2-glb:/backend/assets/src/glb/storage
      - /home/jerand/mygrid2-images:/backend/assets/src/images/storage

  api:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - db
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - TOKEN_EXPIRES_MINUTES=${TOKEN_EXPIRES_MINUTES}
      - REFRESH_TOKEN_EXPIRES_MINUTES=${REFRESH_TOKEN_EXPIRES_MINUTES}
      - API_URL=${API_URL}
      - WEBSITE_URL=${WEBSITE_URL}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - CONFIRMED_EMAIL_URL=${CONFIRMED_EMAIL_URL}
      - CONFIRMED_EMAIL_REDIRECT_URL=${CONFIRMED_EMAIL_REDIRECT_URL}
      - MS_ASSETS_URL=${MS_ASSETS_URL}
      - MS_MAILINGS_URL=${MS_MAILINGS_URL}
      - MS_OPENF1_URL=${MS_OPENF1_URL}
      - EXPO_ACCESS_TOKEN=${EXPO_ACCESS_TOKEN}
      - APPLE_DEV_NONCE_SECRET=${APPLE_DEV_NONCE_SECRET}
      - APPLE_APP_ISS=${APPLE_APP_ISS}
      - APPLE_CLIENT_ID=${APPLE_CLIENT_ID}
      - APPLE_DEV_KID=${APPLE_DEV_KID}
      - APPLE_DEV_PRIVATE_KEY=${APPLE_DEV_PRIVATE_KEY}
      - APPLE_DEV_SUB=${APPLE_DEV_SUB}
      - GOOGLE_AUTH_EXPO_CLIENT_ID=${GOOGLE_AUTH_EXPO_CLIENT_ID}
      - GOOGLE_AUTH_ANDROID_CLIENT_ID=${GOOGLE_AUTH_ANDROID_CLIENT_ID}
      - GOOGLE_AUTH_IOS_CLIENT_ID=${GOOGLE_AUTH_IOS_CLIENT_ID}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

volumes:
  postgres-db:

networks:
  app-network:
    driver: bridge