name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-slim
    env:
      DEBUG: 0

      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mygrid2
      DB_USER: postgres
      DB_PASSWORD: password123

      DATABASE_URL: postgres://postgres:password123@db:5432/mygrid2?sslmode=disable

      OPENF1_API_USERNAME: username
      OPENF1_API_PASSWORD: password123

      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_CRYPTAGE: ${{ secrets.MAIL_CRYPTAGE }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERLABEL: ${{ secrets.MAIL_USERLABEL }}
      MAIL_ALIAS: ${{ secrets.MAIL_ALIAS }}
      MAIL_DOMAIN: ${{ secrets.MAIL_DOMAIN }}
      MAIL_LOGIN: ${{ secrets.MAIL_LOGIN }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      TOKEN_EXPIRES_MINUTES: 12
      REFRESH_TOKEN_EXPIRES_MINUTES: 24
      WEBSITE_URL: https://mygrid-app.com/
      CONFIRMED_EMAIL_URL: https://mygrid-app.com/
      MS_MAILINGS_URL: https://mygrid-app.com/
      MS_OPENF1_URL: https://mygrid-app.com/
      MS: 0
      APPLE_DEV_NONCE_SECRET: abc123
      APPLE_APP_ISS: ABC123
      APPLE_CLIENT_ID: ${{ secrets.APPLE_CLIENT_ID }}
      APPLE_DEV_KID: ABC123
      APPLE_DEV_PRIVATE_KEY: ABC123
      APPLE_DEV_SUB: ${{ secrets.APPLE_CLIENT_ID }}
      GOOGLE_AUTH_EXPO_CLIENT_ID: abc123
      GOOGLE_AUTH_ANDROID_CLIENT_ID: abc123
      GOOGLE_AUTH_IOS_CLIENT_ID: abc123

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull git repo
        uses: actions/checkout@v4
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: Docker compose
        run: docker compose up -d
      - name: Run tests
        run: |
          docker container exec -it mygrid2-api-1 sh
          poetry run pytest -s -v

  docker-build:
    runs-on: ubuntu-latest

    needs: [ci]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mygrid2:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [ci, docker-build]

    steps:
      - name: Deploy to prod VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/MyGrid2/
            docker login
            docker pull jandriambolisoa/mygrid2:latest
            docker compose up --force-recreate -d